#:kivy 1.10.0

<Test>:


<PlotClass>:
	canvas.before:
		Color:
			rgba: .8, 1, 0, .5
		Rectangle:
			pos: self.pos
			size: self.size
	Label:
		text_size: self.size
		text: 'Output Screen'

<MetUI>:
    size: 300, 100
	PlotClass:
		id: test
    BoxLayout:
		orientation: 'vertical'
		cols: 2
        Button:
			on_touch_down: test.DrawDifferent()
            text: 'Parameter 1: '

        Label:
            text: 'Parameter 2: '

